# EDA - Solar and Lunar Eclipses data
Short EDA on dataset to get an understanding of the data

In [7]:
import pandas as pd 
from pathlib import Path


DATA_PATH = Path.cwd().parent / "backend" / "data"

# Read data 
df = pd.read_csv(DATA_PATH / "lunar.csv")
df.head(3)

,Catalog Number,Calendar Date,Eclipse Time,Delta T (s),Lunation Number,Saros Number,Eclipse Type,Quincena Solar Eclipse,Gamma,Penumbral Magnitude,Umbral Magnitude,Latitude,Longitude,Penumbral Eclipse Duration (m),Partial Eclipse Duration (m),Total Eclipse Duration (m)
0,1,-1999 June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,-,-
1,2,-1999 November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,-,-
2,3,-1998 May 17,05:47:36,46416,-49445,-11,P,-t,0.8988,1.2105,0.2069,13S,89E,281.7,102.7,-

In [8]:
# See what columns there are
df.columns

Index(['Catalog Number', 'Calendar Date', 'Eclipse Time', 'Delta T (s)',
       'Lunation Number', 'Saros Number', 'Eclipse Type',
       'Quincena Solar Eclipse', 'Gamma', 'Penumbral Magnitude',
       'Umbral Magnitude', 'Latitude', 'Longitude',
       'Penumbral Eclipse Duration (m)', 'Partial Eclipse Duration (m)',
       'Total Eclipse Duration (m)'],
      dtype='str')

In [9]:
# See how many rows and columns there are
rows, cols = df.shape
print(f"rows: {rows}, columns: {cols}")

rows: 12064, columns: 16

In [10]:
# See information about columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12064 entries, 0 to 12063
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Catalog Number                  12064 non-null  int64
 1   Calendar Date                   12064 non-null  str
 2   Eclipse Time                    12064 non-null  str
 3   Delta T (s)                     12064 non-null  int64
 4   Lunation Number                 12064 non-null  int64
 5   Saros Number                    12064 non-null  int64
 6   Eclipse Type                    12064 non-null  str
 7   Quincena Solar Eclipse          12064 non-null  str
 8   Gamma                           12064 non-null  float64
 9   Penumbral Magnitude             12064 non-null  float64
 10  Umbral Magnitude                12064 non-null  float64
 11  Latitude                        12064 non-null  str
 12  Longitude                       12064 non-null  str
 13  Penumbral Eclipse Duration (m)  12064 non-null  float64
 14  Partial Eclipse Duration (m)    12064 non-null  str
 15  Total Eclipse Duration (m)      12064 non-null  str
dtypes: float64(4), int64(4), str(8)
memory usage: 1.5 MB

In [11]:
df.describe()

,Catalog Number,Delta T (s),Lunation Number,Saros Number,Gamma,Penumbral Magnitude,Umbral Magnitude,Penumbral Eclipse Duration (m)
count,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000,12064.000000
mean,6032.500000,12116.476044,-18531.392822,80.505056,0.002490,1.418656,0.400175,269.971941
std,3482.721158,13584.785584,17887.218741,48.416007,0.910505,0.832263,0.832954,79.945444
min,1.000000,-6.000000,-49456.000000,-20.000000,-1.582700,0.000400,-1.095800,5.200000
25%,3016.750000,962.000000,-33923.250000,40.000000,-0.788825,0.684425,-0.334000,223.100000
50%,6032.500000,5597.000000,-18445.500000,80.000000,0.001750,1.417450,0.400450,295.000000
75%,9048.250000,20901.500000,-3067.750000,121.000000,0.791725,2.136900,1.117925,327.800000
max,12064.000000,46437.000000,12378.000000,183.000000,1.579100,2.908900,1.882100,379.500000

In [12]:
# Replace blank spaces for easier handeling

df.columns = df.columns.str.replace(' ','_')
df.head(4)

,Catalog_Number,Calendar_Date,Eclipse_Time,Delta_T_(s),Lunation_Number,Saros_Number,Eclipse_Type,Quincena_Solar_Eclipse,Gamma,Penumbral_Magnitude,Umbral_Magnitude,Latitude,Longitude,Penumbral_Eclipse_Duration_(m),Partial_Eclipse_Duration_(m),Total_Eclipse_Duration_(m)
0,1,-1999 June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,-,-
1,2,-1999 November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,-,-
2,3,-1998 May 17,05:47:36,46416,-49445,-11,P,-t,0.8988,1.2105,0.2069,13S,89E,281.7,102.7,-
3,4,-1998 November 11,05:15:58,46404,-49439,-6,P,-a,-0.4644,2.0382,0.9740,12N,113E,343.4,200.8,-

## Check counts/amounts

In [13]:
df["Saros_Number"].value_counts().head(4)

Saros_Number
47    86
65    86
27    85
26    85
Name: count, dtype: int64

In [14]:
df["Eclipse_Type"].value_counts()

Eclipse_Type
P     4207
N     4020
T     1405
T+    1042
T-    1032
Nx     141
Ne     115
Nb     102
Name: count, dtype: int64

In [15]:
df["Quincena_Solar_Eclipse"].value_counts().head(4)

Quincena_Solar_Eclipse
a-    2477
-a    2471
t-    1788
-t    1787
Name: count, dtype: int64

In [16]:
df["Gamma"].value_counts().head(4)

Gamma
-0.4598    5
 0.8742    4
 1.3364    4
-0.0887    4
Name: count, dtype: int64

In [17]:
df["Latitude"].value_counts().head(4)

Latitude
23S    544
22S    533
23N    514
22N    511
Name: count, dtype: int64

In [18]:
df["Longitude"].value_counts().head(4)

Longitude
87E     53
64E     50
64W     49
129W    48
Name: count, dtype: int64

## Extract years from dates

In [19]:
import duckdb

# First check
duckdb.sql("""--sql
SELECT Calendar_Date, SUBSTRING(Calendar_Date, 1, 5) AS test
FROM df
LIMIT 5;
""").df()

# Noticed became wrong when year was shorter than 4 digits or missing -

       Calendar_Date   test
0      -1999 June 26  -1999
1  -1999 November 21  -1999
2       -1998 May 17  -1998
3  -1998 November 11  -1998
4        -1997 May 6  -1997

In [20]:
# Create Year column and extract year, also remove year from Date column

df["Year"] = df["Calendar_Date"].str.extract(r"^(-?\d{1,4})", expand=False)
df["Year"] = pd.to_numeric(df["Year"])
df["Calendar_Date"] = df["Calendar_Date"].str.replace(r"^(-?\d{1,4})", "", regex=True)
df.head(2)

,Catalog_Number,Calendar_Date,Eclipse_Time,Delta_T_(s),Lunation_Number,Saros_Number,Eclipse_Type,Quincena_Solar_Eclipse,Gamma,Penumbral_Magnitude,Umbral_Magnitude,Latitude,Longitude,Penumbral_Eclipse_Duration_(m),Partial_Eclipse_Duration_(m),Total_Eclipse_Duration_(m),Year
0,1,June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,-,-,-1999
1,2,November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,-,-,-1999

In [21]:
df["Year"].value_counts().head(5)

Year
-1926    5
-1796    5
-1731    5
-1275    5
-1210    5
Name: count, dtype: int64

## Create column Centuries

In [22]:
# creation
import numpy as np

df["Century"] = np.where(
    df["Year"] > 0,
    np.ceil(df["Year"] / 100),
    np.floor(df["Year"] / 100)
).astype(int)

df.head(3)

,Catalog_Number,Calendar_Date,Eclipse_Time,Delta_T_(s),Lunation_Number,Saros_Number,Eclipse_Type,Quincena_Solar_Eclipse,Gamma,Penumbral_Magnitude,Umbral_Magnitude,Latitude,Longitude,Penumbral_Eclipse_Duration_(m),Partial_Eclipse_Duration_(m),Total_Eclipse_Duration_(m),Year,Century
0,1,June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,-,-,-1999,-20
1,2,November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,-,-,-1999,-20
2,3,May 17,05:47:36,46416,-49445,-11,P,-t,0.8988,1.2105,0.2069,13S,89E,281.7,102.7,-,-1998,-20

In [23]:
def century(century):
    century_str = str(century)
    if century_str in ["11", "12", "13"]:
        suffix = "th"    
    elif century_str[-1] == "1":
        suffix = "st"
    elif century_str[-1] == "2":
        suffix = "nd"
    elif century_str[-1] == "3":
        suffix = "rd"
    else:
        suffix = "th"

    if century < 0:
        return f"{century_str}{suffix} century BCE"
    else:
        return f"{century_str}{suffix} century"

df["Century"] = df["Century"].apply(century)

In [24]:
df.head(2)

,Catalog_Number,Calendar_Date,Eclipse_Time,Delta_T_(s),Lunation_Number,Saros_Number,Eclipse_Type,Quincena_Solar_Eclipse,Gamma,Penumbral_Magnitude,Umbral_Magnitude,Latitude,Longitude,Penumbral_Eclipse_Duration_(m),Partial_Eclipse_Duration_(m),Total_Eclipse_Duration_(m),Year,Century
0,1,June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,-,-,-1999,-20th century BCE
1,2,November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,-,-,-1999,-20th century BCE

In [25]:
# Check what centurie has most eclpises 

df["Century"].value_counts().head(4)

Century
12th century         259
29th century         259
-18th century BCE    256
18th century         256
Name: count, dtype: int64

## Eclipse durations

In [26]:
# replace - with 0

def convert_time(column):
    df[column] = df[column].str.replace("-", "0")
    df[column] = pd.to_numeric(df[column], errors="coerce").fillna(0)

In [27]:
convert_time("Partial_Eclipse_Duration_(m)")
convert_time("Total_Eclipse_Duration_(m)")

df.head(2)

,Catalog_Number,Calendar_Date,Eclipse_Time,Delta_T_(s),Lunation_Number,Saros_Number,Eclipse_Type,Quincena_Solar_Eclipse,Gamma,Penumbral_Magnitude,Umbral_Magnitude,Latitude,Longitude,Penumbral_Eclipse_Duration_(m),Partial_Eclipse_Duration_(m),Total_Eclipse_Duration_(m),Year,Century
0,1,June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,0.0,0.0,-1999,-20th century BCE
1,2,November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,0.0,0.0,-1999,-20th century BCE

In [28]:
# Calculate total time for eclipse

df["Eclipse_Total_Time"] = df["Penumbral_Eclipse_Duration_(m)"] + df["Partial_Eclipse_Duration_(m)"] + df["Total_Eclipse_Duration_(m)"]
df.head(2)

,Catalog_Number,Calendar_Date,Eclipse_Time,Delta_T_(s),Lunation_Number,Saros_Number,Eclipse_Type,Quincena_Solar_Eclipse,Gamma,Penumbral_Magnitude,Umbral_Magnitude,Latitude,Longitude,Penumbral_Eclipse_Duration_(m),Partial_Eclipse_Duration_(m),Total_Eclipse_Duration_(m),Year,Century,Eclipse_Total_Time
0,1,June 26,14:13:28,46437,-49456,17,N,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,0.0,0.0,-1999,-20th century BCE,268.8
1,2,November 21,20:23:49,46427,-49451,-16,N,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,0.0,0.0,-1999,-20th century BCE,233.4

In [29]:
# Check calculation

df[["Penumbral_Eclipse_Duration_(m)", 
    "Partial_Eclipse_Duration_(m)", 
    "Total_Eclipse_Duration_(m)",
    "Eclipse_Total_Time"]].head(3)

,Penumbral_Eclipse_Duration_(m),Partial_Eclipse_Duration_(m),Total_Eclipse_Duration_(m),Eclipse_Total_Time
0,268.8,0.0,0.0,268.8
1,233.4,0.0,0.0,233.4
2,281.7,102.7,0.0,384.4

In [30]:
# AVG, MEDIAN....
df["Eclipse_Total_Time"].describe()

count    12064.000000
mean       404.625058
std        193.642630
min          5.200000
25%        223.100000
50%        432.100000
75%        581.225000
max        719.300000
Name: Eclipse_Total_Time, dtype: float64

## Replace eclipse type with name of type

In [31]:
df["Eclipse_Group_Type"] = df["Eclipse_Type"].replace({
    "P": "Partial",
    "N": "Penumbral",
    "T": "Total",
    "T+": "Total",
    "T-": "Total",
    "Nx": "Penumbral",
    "Ne": "Penumbral",
    "Nb": "Penumbral"
})

In [32]:
# replace P -> Partial.....

df["Eclipse_Type"]  = df["Eclipse_Type"].replace({
    "P": "Partial",
    "N": "Penumbral",
    "T": "Total",
    "T+": "Total (north)",
    "T-": "Total (south)",
    "Nx": "Penumbral (total)",
    "Ne": "Penumbral (end)",
    "Nb": "Penumbral (begin)"
})

In [33]:
df.head(5)

,Catalog_Number,Calendar_Date,Eclipse_Time,Delta_T_(s),Lunation_Number,Saros_Number,Eclipse_Type,Quincena_Solar_Eclipse,Gamma,Penumbral_Magnitude,Umbral_Magnitude,Latitude,Longitude,Penumbral_Eclipse_Duration_(m),Partial_Eclipse_Duration_(m),Total_Eclipse_Duration_(m),Year,Century,Eclipse_Total_Time,Eclipse_Group_Type
0,1,June 26,14:13:28,46437,-49456,17,Penumbral,t-,-1.0981,0.8791,-0.1922,24S,22W,268.8,0.0,0.0,-1999,-20th century BCE,268.8,Penumbral
1,2,November 21,20:23:49,46427,-49451,-16,Penumbral,-a,-1.1155,0.8143,-0.1921,15N,98W,233.4,0.0,0.0,-1999,-20th century BCE,233.4,Penumbral
2,3,May 17,05:47:36,46416,-49445,-11,Partial,-t,0.8988,1.2105,0.2069,13S,89E,281.7,102.7,0.0,-1998,-20th century BCE,384.4,Partial
3,4,November 11,05:15:58,46404,-49439,-6,Partial,-a,-0.4644,2.0382,0.9740,12N,113E,343.4,200.8,0.0,-1998,-20th century BCE,544.2,Partial
4,5,May 6,18:57:01,46392,-49433,-1,Total (north),pp,0.1003,2.6513,1.6963,11S,92W,322.8,213.5,98.2,-1997,-20th century BCE,634.5,Total